spring:
  application:
    name: Gateway-Service
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: Course-Service
              uri: http://localhost:8082
              predicates:
                - Path=/api/courses/**
            - id: Identity-Service
              uri: http://localhost:8080
              predicates:
                - Path=/api/auth/**
jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
  expiration_access_token: 900000
  expiration_refresh_token: 86400000
server:
  port: 8888